services:
  api:
    image: ca:api
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Test2025
